=== aliemadaboshosha/attendance-program/xml/AttendanceData_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="students_Attendance">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="attendace" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="date" type="xs:date"/>
              <xs:element name="Courses_attendance">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Course_attendance" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Course_id" type="xs:integer"/>
                          <xs:element name="Class_id" type="xs:integer"/>
                          <xs:element name="students">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="student_id" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== aliemadaboshosha/attendance-program/xml/AttendanceData.xml
<students_Attendance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\PD(ITI Mansoura)\C#\project-attendance Management\sprint2\attendance-program2\xml\AttendanceData_Schema.xsd">
	<attendace>
	
	
	
		<date>2024-01-08</date>
		<Courses_attendance>
		
		
		
			<Course_attendance>
				<Course_id>1</Course_id>
				<Class_id>1000</Class_id>
				<students>
					<student_id>201</student_id>
					<student_id>1000</student_id>
				</students>
			</Course_attendance>
			
			
			
			<Course_attendance>
				<Course_id>2</Course_id>
				<Class_id>1001</Class_id>
				<students>
					<student_id>202</student_id>
				</students>
			</Course_attendance>
		</Courses_attendance>
	</attendace>





	<attendace>
	
	<date>2024-01-09</date>
		<Courses_attendance>
			<Course_attendance>
				<Course_id>1</Course_id>
				<Class_id>1000</Class_id>
				<students>
					<student_id>201</student_id>
					<student_id>1000</student_id>
				</students>
			</Course_attendance>
			<Course_attendance>
				<Course_id>2</Course_id>
				<Class_id>1001</Class_id>
				<students>
					<student_id>202</student_id>
				</students>
			</Course_attendance>
		</Courses_attendance>
	</attendace>
	
	
	
	
	
	<attendace>
		<date>2024-01-11</date>
		<Courses_attendance>
			<Course_attendance>
				<Course_id>2</Course_id>
				<Class_id>1000</Class_id>
				<students>
					<student_id>201</student_id>
				</students>
			</Course_attendance>
		</Courses_attendance>
	</attendace>
	
	
	
		
	<attendace>
		<date>2024-01-28</date>
		
		<Courses_attendance>
		
			<Course_attendance>
				<Course_id>3</Course_id>
				<Class_id>1000</Class_id>
				<students>
					<student_id>201</student_id>
				</students>
			</Course_attendance>
			
		</Courses_attendance>
		
	</attendace>
	
		<attendace>
		<date>2024-01-29</date>
		
		<Courses_attendance>
		
			<Course_attendance>
				<Course_id>3</Course_id>
				<Class_id>1000</Class_id>
				<students>
					<student_id>201</student_id>
				</students>
			</Course_attendance>
			
		</Courses_attendance>
		
		</attendace>
	
			<attendace>
		<date>2024-01-30</date>
		
		<Courses_attendance>
		
			<Course_attendance>
				<Course_id>1</Course_id>
				<Class_id>1000</Class_id>
				<students>
					<student_id>201</student_id>
				</students>
			</Course_attendance>
			
		</Courses_attendance>
		
	</attendace>
	
	
	
</students_Attendance>
